-- CANTIDAD DE GRUPOS SANGUINEOS
SELECT COUNT(*) FROM grupo_sanguineo;

-- CANTIDAD DE PACIENTES
SELECT COUNT(*) FROM paciente;

-- CANTIDAD DE HISTORIAS CLINICAS
SELECT COUNT(*) FROM historia_clinica;

-- VERIFICAR FK HUERFANAS

-- NO PUEDE HABER UNA HISTORIA CLINICA SIN GRUPO SANGUINEO
SELECT COUNT(*)
FROM historia_clinica hc
LEFT JOIN grupo_sanguineo gs ON hc.id_grupo_sanguineo = gs.id
WHERE gs.id IS NULL;

-- VERIFICO QUE CADA HISTORIA CLINICA TENGA EXACTAMENTE UN PACIENTE
SELECT COUNT(*)
FROM historia_clinica hc
LEFT JOIN paciente p ON p.id_historia = hc.id
WHERE p.id IS NULL;

-- VERIFICO QUE CADA PACIENTE TENGA EXACTAMENTE UNA HISTORIA CLINICA
SELECT COUNT(*)
FROM paciente p
LEFT JOIN historia_clinica hc ON p.id_historia = hc.id
WHERE hc.id IS NULL;