plugins {
    id 'java'
}

group 'com.tup'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'

    // LIBRERÍA LOMBOK (Anotaciones para simplificar código)
    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'

    // LIBRERÍAS NUEVAS PARA JPA - HIBERNATE - H2
    implementation 'jakarta.persistence:jakarta.persistence-api:3.1.0'
    implementation 'org.hibernate.orm:hibernate-core:6.4.4.Final'
    implementation 'com.h2database:h2:2.2.224'
}

test {
    useJUnitPlatform()
}